begin;

alter type public.user_status add value if not exists 'deactivated';

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check
  check (role = any (array[
    'user'::text,
    'gym_owner'::text,
    'gym_staff'::text,
    'staff'::text,
    'admin'::text,
    'super_admin'::text,
    'nagarsevak'::text
  ]));

create table if not exists public.auth_rate_limits (
  key_hash text primary key,
  scope text not null,
  attempts integer not null default 0 check (attempts >= 0),
  window_started_at timestamptz not null default now(),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.password_reset_tokens (
  token_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  requested_ip_hash text,
  created_at timestamptz not null default now()
);

create index if not exists password_reset_tokens_user_created_idx
  on public.password_reset_tokens (user_id, created_at desc);
create index if not exists password_reset_tokens_expiry_idx
  on public.password_reset_tokens (expires_at)
  where used_at is null;

create table if not exists public.auth_security_events (
  event_id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email_hash text,
  ip_hash text,
  event_type text not null,
  success boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists auth_security_events_user_created_idx
  on public.auth_security_events (user_id, created_at desc);
create index if not exists auth_security_events_type_created_idx
  on public.auth_security_events (event_type, created_at desc);

alter table public.auth_rate_limits enable row level security;
alter table public.password_reset_tokens enable row level security;
alter table public.auth_security_events enable row level security;

revoke all on public.auth_rate_limits from anon, authenticated;
revoke all on public.password_reset_tokens from anon, authenticated;
revoke all on public.auth_security_events from anon, authenticated;
revoke all on sequence public.auth_security_events_event_id_seq from anon, authenticated;

create or replace function public.consume_auth_rate_limit(
  p_key_hash text,
  p_scope text,
  p_limit integer,
  p_window_seconds integer,
  p_block_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.auth_rate_limits%rowtype;
  current_time timestamptz := clock_timestamp();
  next_attempts integer;
begin
  if coalesce(length(p_key_hash), 0) < 16
    or coalesce(length(p_scope), 0) < 1
    or p_limit < 1
    or p_window_seconds < 1
    or p_block_seconds < 1 then
    raise exception 'Invalid auth rate-limit arguments';
  end if;

  select * into current_row
  from public.auth_rate_limits
  where key_hash = p_key_hash
  for update;

  if not found then
    insert into public.auth_rate_limits (
      key_hash,
      scope,
      attempts,
      window_started_at,
      blocked_until,
      updated_at
    ) values (
      p_key_hash,
      p_scope,
      1,
      current_time,
      null,
      current_time
    );
    return true;
  end if;

  if current_row.blocked_until is not null and current_row.blocked_until > current_time then
    update public.auth_rate_limits
    set updated_at = current_time
    where key_hash = p_key_hash;
    return false;
  end if;

  if current_row.window_started_at + make_interval(secs => p_window_seconds) <= current_time then
    update public.auth_rate_limits
    set scope = p_scope,
        attempts = 1,
        window_started_at = current_time,
        blocked_until = null,
        updated_at = current_time
    where key_hash = p_key_hash;
    return true;
  end if;

  next_attempts := current_row.attempts + 1;

  if next_attempts > p_limit then
    update public.auth_rate_limits
    set scope = p_scope,
        attempts = next_attempts,
        blocked_until = current_time + make_interval(secs => p_block_seconds),
        updated_at = current_time
    where key_hash = p_key_hash;
    return false;
  end if;

  update public.auth_rate_limits
  set scope = p_scope,
      attempts = next_attempts,
      blocked_until = null,
      updated_at = current_time
  where key_hash = p_key_hash;

  return true;
end;
$$;

revoke all on function public.consume_auth_rate_limit(text, text, integer, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_auth_rate_limit(text, text, integer, integer, integer) to service_role;

commit;
