import crypto from 'crypto';
import { supabaseAdmin, cleanEmail, fail, normalizeRole, publicUser, getSingle, nowIso, isAdminProfile } from './productionCore.js';

const OTP_TTL_MINUTES = Number(process.env.OTP_TTL_MINUTES || 10);
const OTP_HASH_SECRET = process.env.OTP_HASH_SECRET || process.env.SUPABASE_SERVICE_ROLE_KEY;

export const getProfile = (userId) => getSingle('profiles', (q) => q.eq('user_id', userId));

export async function upsertProfile(authUser, overrides = {}) {
  const meta = authUser?.user_metadata || {};
  const existing = await getProfile(authUser.id).catch(() => null);
  const role = normalizeRole(overrides.role || existing?.role || meta.role);
  const row = {
    user_id: authUser.id,
    email: cleanEmail(authUser.email || overrides.email),
    role,
    status: overrides.status || existing?.status || 'active',
    source: overrides.source || existing?.source || (role === 'gym_owner' ? 'gym_owner' : 'app'),
    full_name: overrides.full_name || overrides.name || overrides.owner_name || existing?.full_name || meta.full_name || meta.name || meta.owner_name || null,
    phone: overrides.phone || overrides.mobile || existing?.phone || meta.phone || meta.mobile || null,
    avatar_url: overrides.avatar_url || existing?.avatar_url || meta.avatar_url || meta.picture || null,
    metadata: { ...(existing?.metadata || {}), ...meta, ...overrides },
    updated_at: nowIso(),
  };
  const { data, error } = await supabaseAdmin.from('profiles').upsert(row, { onConflict: 'user_id' }).select('*').single();
  if (error) throw fail(error.message, 500);
  await supabaseAdmin.from('user_roles').upsert({ user_id: authUser.id, role }, { onConflict: 'user_id,role' }).catch(() => null);
  return data;
}

export async function findUserByEmail(email) {
  const target = cleanEmail(email);
  for (let page = 1; page <= 10; page += 1) {
    const { data, error } = await supabaseAdmin.auth.admin.listUsers({ page, perPage: 1000 });
    if (error) return null;
    const found = (data?.users || []).find((user) => cleanEmail(user.email) === target);
    if (found) return found;
    if (!data?.users?.length || data.users.length < 1000) return null;
  }
  return null;
}

function otpHash(email, otp, purpose) {
  return crypto.createHmac('sha256', OTP_HASH_SECRET).update(`${cleanEmail(email)}:${purpose}:${String(otp).trim()}`).digest('hex');
}

export async function createOtpChallenge({ email, session, profile, authUser, purpose = 'login', role }) {
  const clean = cleanEmail(email);
  const otp = String(Math.floor(100000 + Math.random() * 900000));
  const row = {
    email: clean,
    purpose,
    role: normalizeRole(role || profile?.role || authUser?.user_metadata?.role),
    otp_hash: otpHash(clean, otp, purpose),
    session_payload: session || {},
    auth_user_payload: authUser || {},
    profile_payload: profile || {},
    expires_at: new Date(Date.now() + OTP_TTL_MINUTES * 60000).toISOString(),
    consumed_at: null,
    attempts: 0,
  };
  const { error } = await supabaseAdmin.from('auth_otp_challenges').upsert(row, { onConflict: 'email,purpose' });
  if (error) throw fail(error.message, 500);
  return { requires_otp: true, purpose, email: clean, role: row.role, message: 'Verification code generated by backend.' };
}

export async function consumeOtpChallenge(email, token, purpose) {
  const clean = cleanEmail(email);
  const challenge = await getSingle('auth_otp_challenges', (q) => q.eq('email', clean).eq('purpose', purpose));
  if (!challenge || challenge.consumed_at) throw fail('No pending verification code. Please start again.', 400);
  if (new Date(challenge.expires_at).getTime() < Date.now()) {
    await supabaseAdmin.from('auth_otp_challenges').delete().eq('challenge_id', challenge.challenge_id);
    throw fail('Verification code expired. Please resend code.', 400);
  }
  if (Number(challenge.attempts || 0) >= 5) throw fail('Too many OTP attempts. Please request a new code.', 429);
  if (challenge.otp_hash !== otpHash(clean, token, purpose)) {
    await supabaseAdmin.from('auth_otp_challenges').update({ attempts: Number(challenge.attempts || 0) + 1 }).eq('challenge_id', challenge.challenge_id);
    throw fail('Invalid verification code', 400);
  }
  await supabaseAdmin.from('auth_otp_challenges').delete().eq('challenge_id', challenge.challenge_id);
  return challenge;
}

export async function requireAuth(req, _res, next) {
  try {
    const token = String(req.headers.authorization || '').replace(/^Bearer\s+/i, '');
    if (!token) throw fail('Missing bearer token', 401);
    const { data, error } = await supabaseAdmin.auth.getUser(token);
    if (error || !data?.user) throw fail('Invalid or expired token', 401);
    let profile = await getProfile(data.user.id);
    if (!profile) profile = await upsertProfile(data.user);
    if (profile.status === 'blocked') throw fail('Account is blocked', 403);
    req.authUser = data.user;
    req.userProfile = profile;
    req.user = publicUser(profile, data.user);
    next();
  } catch (error) { next(error); }
}

export function requireAdmin(req, _res, next) {
  if (!isAdminProfile(req.userProfile)) return next(fail('Admin access required', 403));
  next();
}
export function requireSuperAdmin(req, _res, next) {
  if (normalizeRole(req.userProfile?.role) !== 'super_admin') return next(fail('Super admin access required', 403));
  next();
}
